In [ ]:
a=[3,5,8,2,9]
a.sort()
print(a)

[2, 3, 5, 8, 9]


In [ ]:
b=[5,8,34,65,23]
c=sorted(b)
print(c)

[5, 8, 23, 34, 65]


In [ ]:
a=(34,54,64,23)
b=sorted(a)
print(a)
print(b)

(34, 54, 64, 23)
[23, 34, 54, 64]


In [2]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B=np.linspace(3,4,12).reshape(3,4)
print(B)

[[3.         3.09090909 3.18181818 3.27272727]
 [3.36363636 3.45454545 3.54545455 3.63636364]
 [3.72727273 3.81818182 3.90909091 4.        ]]


In [ ]:
D=np.array([43,54,76,34,76,23,34,65,76]).reshape(3,3,1)
print(D)


[[[43]
  [54]
  [76]]

 [[34]
  [76]
  [23]]

 [[34]
  [65]
  [76]]]


In [ ]:
d=np.array([43,53,5,65,63,34,23,54])
d.resize(2,2,2)#changes the shape of original array
#reshape - changes needs saving in another variable
print(d)

[[[43 53]
  [ 5 65]]

 [[63 34]
  [23 54]]]


In [ ]:
A=np.array([34,23,43,54])
B=np.array([4,23,43,54])#list will throw an error while arrays iterate themselves
C=A-B
print(C)

[30  0  0  0]


In [ ]:
A=np.array([34,23,43,54])
B=np.array([4,23,43,54])#list will throw an error while arrays iterate themselves
C=A+B
print(C)

[ 38  46  86 108]


In [ ]:
A=np.array([34,23,43,54])
B=np.array([4,23,43,54])#list will throw an error while arrays iterate themselves
C=A*B#one on one multiplication
print(C)

[ 136  529 1849 2916]


In [ ]:
A=np.array([34,23,43,54]).reshape(2,2)
B=np.array([4,23,43,54]).reshape(2,2)#list will throw an error while arrays iterate themselves
print(A)
print("__________________________")
print(B)
print("__________________________")
C=A*B
print(C)

[[34 23]
 [43 54]]
__________________________
[[ 4 23]
 [43 54]]
__________________________
[[ 136  529]
 [1849 2916]]


In [ ]:
A=np.array([34,23,43,54]).reshape(2,2)
B=np.array([4,23,43,54]).reshape(2,2)#list will throw an error while arrays iterate themselves
print(A)
print("__________________________")
print(B)
print("__________________________")
C=A@B
print(C)

[[34 23]
 [43 54]]
__________________________
[[ 4 23]
 [43 54]]
__________________________
[[1125 2024]
 [2494 3905]]


In [ ]:
A= np.array([233.3,23.5,54.3,43.6,34.8])
print(A.max())#max and min only accepts numeric datatypes
print(A.min())

233.3
23.5


In [ ]:
A=np.array([34,23,43,54,25,51,42,75,22]).reshape(3,3)
B=np.array([4,23,43,54]).reshape(2,2)#list will throw an error while arrays iterate themselves
print(A)
print("__________________________")
print(A.max(axis=0)) #axis 0 - column
print("__________________________")
print(A.max(axis=1)) #axis 1 - row


[[34 23 43]
 [54 25 51]
 [42 75 22]]
__________________________
[54 75 51]
__________________________
[43 54 75]


In [ ]:
A=np.array([34,23,43,54,25,51,42,75,22]).reshape(3,3)
B=np.array([4,23,43,54]).reshape(2,2)#list will throw an error while arrays iterate themselves
print(A)
print("__________________________")
print(A.min(axis=0)) #axis 0 - column
print("__________________________")
print(A.min(axis=1)) #axis 1 - row

[[34 23 43]
 [54 25 51]
 [42 75 22]]
__________________________
[34 23 22]
__________________________
[23 25 22]


In [ ]:
A=np.array([34,12,33,14]).reshape(2,2)
B=np.array([4,23,43,31]).reshape(2,2)
print(A)
print("__________________________")
print(B)
print("__________________________")
print("After vertically stacking thr arrays!")
print(np.vstack((A,B)))#vertical stack

[[34 12]
 [33 14]]
__________________________
[[ 4 23]
 [43 31]]
__________________________
After vertically stacking thr arrays!
[[34 12]
 [33 14]
 [ 4 23]
 [43 31]]


In [ ]:
A=np.array([34,12,33,14]).reshape(2,2)
B=np.array([4,23,43,31]).reshape(2,2)
print(A)
print("__________________________")
print(B)
print("__________________________")
print("After vertically stacking thr arrays!")
print(np.hstack((A,B)))#Horizontal stack

[[34 12]
 [33 14]]
__________________________
[[ 4 23]
 [43 31]]
__________________________
After vertically stacking thr arrays!
[[34 12  4 23]
 [33 14 43 31]]


In [ ]:
A=np.array([34,12,33,14]).reshape(2,2)
B=np.array([4,23,43,31]).reshape(2,2)
print(A)
print("__________________________")
print(B)
print("__________________________")
print("After vertically stacking thr arrays!")
print(np.stack((A,B),axis=0))#vstack

[[34 12]
 [33 14]]
__________________________
[[ 4 23]
 [43 31]]
__________________________
After vertically stacking thr arrays!
[[[34 12]
  [33 14]]

 [[ 4 23]
  [43 31]]]


In [ ]:
A=np.array([34,12,33,14]).reshape(2,2)
B=np.array([4,23,43,31]).reshape(2,2)
print(A)
print("__________________________")
print(B)
print("__________________________")
print("After vertically stacking thr arrays!")
print(np.stack((A,B),axis=1))#hstack

[[34 12]
 [33 14]]
__________________________
[[ 4 23]
 [43 31]]
__________________________
After vertically stacking thr arrays!
[[[34 12]
  [ 4 23]]

 [[33 14]
  [43 31]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#no.of rows --> no.of groups
#no.of col in every group --> no.of rows in every group
#[0,0],[1,1]..........


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Splitting arrays
A=np.arange(18).reshape(6,3)#Based on rows and columns the arrays will split into two equal parts.
print(A)
print("After splitting")
#It is to cut as we want like as we want to cut anywhere.
print(np.vsplit(A,(2,5)))#Vertical split
print(np.vsplit(A,(2,4)))# ''
print(np.vsplit(A,(2,3)))# ''
print(np.hsplit(A,(2,5)))#Horizontal split


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([], shape=(6, 0), dtype=int64)]


In [ ]:
A = np.array([14,23,43,12,56,45,15,21,32]).reshape(3,3)
print(A)
print(A.argmax(axis=0))#It take in a vertical way
print(A.argmax(axis=1))#It takes in a horigontal way

[[14 23 43]
 [12 56 45]
 [15 21 32]]
[2 1 1]
[2 1 2]


In [ ]:
A = np.array([14,23,43,12,56,45,15,21,32]).reshape(3,3)
print(A)
print(A.argmin(axis=0))
print(A.argmin(axis=1))

[[14 23 43]
 [12 56 45]
 [15 21 32]]
[1 2 2]
[0 0 0]


In [ ]:
A = np.array([14,23,43,12,56,45,15,21,32]).reshape(3,3)
print(A)
print(A.argmax())
print(A.argmin())

[[14 23 43]
 [12 56 45]
 [15 21 32]]
4
3


In [ ]:
#numpy statistics with formulas of mean,median,variance,standard deviation
#mean,median,std,var
A = np.array([21,32,12,43,44,56])
print("Mean: ",np.mean(A))
print("Median: ",np.median(A))
print("Variance: ",np.var(A))
print("Standard Dev: ",np.std(A))

Mean:  34.666666666666664
Median:  37.5
Variance:  219.8888888888889
Standard Dev:  14.828650946356817


In [ ]:
#trigonometry
A=np.pi # Printing the radius
print(A)
np.rad2deg(A)

3.141592653589793


180.0

In [ ]:
A = np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(A)
np.rad2deg(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


array([ 45.,  60.,  90., 180.])

In [ ]:
B= np.array([32,12,43,33,23])
C= np.deg2rad(B)
print(C)

[0.55850536 0.20943951 0.75049158 0.57595865 0.40142573]


In [ ]:
np.sin(C)

array([0.52991926, 0.20791169, 0.68199836, 0.54463904, 0.39073113])

In [ ]:
np.cos(C)

array([0.8480481 , 0.9781476 , 0.7313537 , 0.83867057, 0.92050485])

In [ ]:
np.tan(C)

array([0.62486935, 0.21255656, 0.93251509, 0.64940759, 0.42447482])

In [ ]:
np.arcsin(1) #inverse to sin i.e sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #inverse to sin i.e cos^-1

0.0

In [ ]:
np.arctan(1) #inverse to sin i.e tan^-1

0.7853981633974483

In [ ]:
a = 6
b = 4
print(np.hypot(a,b)) #Hypothenuse

7.211102550927978


In [14]:
E=np.array([32,64,23,90,76,73])
print(np.searchsorted(E,64)) #outputs the index of a sorted element

1


In [15]:
#Linear algebra and Universal functions
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])

print(np.add(A,B))
print(np.subtract(A,B))

[12 28 70 17 22]
[ 0 20 50  7 14]


In [17]:
print(np.divide(A,B))

[1.  6.  6.  2.4 4.5]


In [16]:
print(np.divmod(A,B))

(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [18]:
print(np.diff(A))

[ 18  36 -48   6]


In [24]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.diff(A))
print(np.mod(A,B))
print(np.sort(A))

[ 18  36 -48   6]
[0 0 0 2 2]
[ 6 12 18 24 60]


In [25]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [26]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


In [30]:
#Rounding
a1= np.around([2.32332,4])
a2=np.fix([-1.3423,2.1342])
a3=np.trunc([2.3223,2.1342])
a4= np.floor([2.32332,4])
a5= np.ceil([2.32332,4])
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[2. 4.]
[-1.  2.]
[2. 2.]
[2. 4.]
[3. 4.]


In [32]:
#Cummulative
a = np.array([45,23,43,65,95])
print(np.cumsum(a))

[ 45  68 111 176 271]


In [33]:
a = np.array([45,23,43,65,95])
print(np.cumprod(a))

[       45      1035     44505   2892825 274818375]


In [35]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [36]:
Ar = np.array([45,65,30])
print(np.lcm.reduce(Ar))
print(np.gcd.reduce(Ar))

1170
5


In [38]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [39]:
from numpy import random as rd

In [46]:
a=rd.rand() #n #default limit 0 to 0.99
print(a)

0.1882036269875602


In [48]:
a=rd.rand(10)#r and (n)
print(a)

[0.46800598 0.73758736 0.19993439 0.50645521 0.76727191 0.55639496
 0.53878722 0.63740662 0.99617077 0.6048965 ]


In [55]:
a=rd.randint(2) #==> limit 0,1,2,3
print(a)

1


In [57]:
a=rd.randint(40,size=6)
print(a)

[18  0 15 19 16 32]


In [58]:
a=rd.randint(40,size=(2,3))
print(a)

[[11 22 39]
 [31 25  3]]


In [60]:
#joins
A=np.array([1,2,3,4])
B=np.array([4,5,6,7])
# 1*4 , 2*5 , 3*6
print(np.inner(A,B))
# 1x(4,5,6,7) , 2x(4,5,6,7) , 3x(4,5,6,7) , 4x(4,5,6,7)
print(np.outer(A,B))

60
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]]


In [63]:
A=np.array([1,2,3])
B=np.array([4,5,6])# Dimensions must be 2 or 3
#1x4 + 2x5 + 3x6
print(np.cross(A,B))

[-3  6 -3]
